services:
  app:
    build: 
      context: .
      target: development
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development
      - DB_HOST=mysql
      - DB_USER=agriconnect
      - DB_PASSWORD=secure_password
      - DB_NAME=agriconnect_dev
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - JWT_SECRET=dev_jwt_secret
      - SMTP_HOST=mailhog
      - SMTP_PORT=1025
    volumes:
      - .:/app
      - /app/node_modules
      - ./uploads:/app/uploads
      - ./logs:/app/logs
    command: npm run dev
    depends_on:
      mysql:
        condition: service_healthy
      redis:
        condition: service_healthy
    restart: unless-stopped
    networks:
      - agriconnect-network

  mysql:
    image: mysql:8.0
    ports:
      - "3307:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=root_password
      - MYSQL_DATABASE=agriconnect_dev
      - MYSQL_USER=agriconnect
      - MYSQL_PASSWORD=secure_password
    volumes:
      - mysql_data_dev:/var/lib/mysql
      - ./database-schema.sql:/docker-entrypoint-initdb.d/01-schema.sql
      - ./database-location-updates.sql:/docker-entrypoint-initdb.d/02-location-updates.sql
      - ./database-soil-collection-updates.sql:/docker-entrypoint-initdb.d/03-soil-collection-updates.sql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      timeout: 20s
      retries: 10
    restart: unless-stopped
    networks:
      - agriconnect-network

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    volumes:
      - redis_data_dev:/data
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      timeout: 10s
      retries: 5
    restart: unless-stopped
    networks:
      - agriconnect-network

  # Enable development tools
  mailhog:
    image: mailhog/mailhog:latest
    ports:
      - "1025:1025"
      - "8025:8025"
    restart: unless-stopped
    networks:
      - agriconnect-network

  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    ports:
      - "8080:80"
    environment:
      - PMA_HOST=mysql
      - PMA_PORT=3306
      - PMA_USER=agriconnect
      - PMA_PASSWORD=secure_password
    depends_on:
      - mysql
    restart: unless-stopped
    networks:
      - agriconnect-network

  redis-commander:
    image: rediscommander/redis-commander:latest
    ports:
      - "8081:8081"
    environment:
      - REDIS_HOSTS=local:redis:6379
    depends_on:
      - redis
    restart: unless-stopped
    networks:
      - agriconnect-network

volumes:
  mysql_data_dev:
    driver: local
  redis_data_dev:
    driver: local

networks:
  agriconnect-network:
    driver: bridge
