/** @type {import('tailwindcss').Config} */
module.exports = {
  content: ['./app/**/*.{js,jsx,ts,tsx}', './components/**/*.{js,jsx,ts,tsx}'],
  theme: {
    extend: {
      fontFamily: {
        poppinsBlack: ['Poppins-Black', 'sans-serif'],
        poppinsBold: ['Poppins-Bold', 'sans-serif'],
        poppinsExtraBold: ['Poppins-ExtraBold', 'sans-serif'],
        poppinsExtraLight: ['Poppins-ExtraLight', 'sans-serif'],
        poppinsLight: ['Poppins-Light', 'sans-serif'],
        poppinsMedium: ['Poppins-Medium', 'sans-serif'],
        poppinsRegular: ['Poppins-Regular', 'sans-serif'],
        poppinsSemiBold: ['Poppins-SemiBold', 'sans-serif'],
        poppinsThin: ['Poppins-Thin', 'sans-serif'],
        robotoBlack: ['Roboto-Black', 'sans-serif'],
        robotoBold: ['Roboto-Bold', 'sans-serif'],
        robotoItalic: ['Roboto-Italic', 'sans-serif'],
        robotoLight: ['Roboto-Light', 'sans-serif'],
        robotoMedium: ['Roboto-Medium', 'sans-serif'],
        robotoRegular: ['Roboto-Regular', 'sans-serif'],
        robotoThin: ['Roboto-Thin', 'sans-serif'],
      },
      colors: {
        primary: {
          main: '#055476',
          light: '#E7F6FC',
          card: '#9BBBC8',
          dark: '#03374A',
          contrastText: '#FFFFFF',
          100: '#006EA6',
          200: '#B1CBFA',
          300: '#C3D9FF',
          400: '#9BBFFF',
          500: '#0286FF',
          600: '#6A85E6',
          700: '#475A99',
          800: '#364573',
          900: '#242B4D',
        },
        grey: {
          100: '#000000',
          200: '#141414',
          300: '#666666',
          400: '#a3a3a3',
          500: '#393E46',
          600: '#E7F6FC',
        },
        background: {
          default: '#FFFFFF',
          paper: '#F8F9FA',
          main: 'white',
        },
        text: {
          primary: '#141414',
          secondary: '#666666',
        },
      },
    },
  },
  presets: [require('nativewind/preset')],
};
